# Generated by Django 5.0.6 on 2024-10-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_star'),
        ('users', '0006_alter_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='star',
        ),
        migrations.AddField(
            model_name='project',
            name='star_profiles',
            field=models.ManyToManyField(blank=True, null=True, related_name='star_projects', to='users.profile'),
        ),
    ]
