# Generated by Django 5.0.6 on 2024-10-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_star_project_star_profiles'),
        ('users', '0006_alter_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='star_profiles',
            field=models.ManyToManyField(blank=True, related_name='star_projects', to='users.profile'),
        ),
    ]
